name: flutter_device_apps
description: App-facing API for listing/inspecting installed apps (federated).
version: 0.6.0

repository: https://github.com/okmsbun/flutter_device_apps
issue_tracker: https://github.com/okmsbun/flutter_device_apps/issues
topics:
  - flutter
  - plugin
  - app-management
  - installed-apps
  - package-manager

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_device_apps_android: ^0.6.0
  flutter_device_apps_platform_interface: ^0.6.0

dev_dependencies:
  flutter_lints: ^6.0.0

flutter:
  plugin:
    platforms:
      android:
        default_package: flutter_device_apps_android
